config/routes.rb
Rails.application.routes.draw do
  resources :comments

  # root
  root 'welcome#index'

  # use devise for users
  devise_for :users

  # resources
  resources :posts do
    resources :comments, :only => [:create]
  end

  # session routes
  devise_scope :user do
    get "/login" => "devise/sessions#new"
    get "/logout" => "devise/sessions#destroy"
  end

  # admin routes
  get '/admin' => 'admin/users#index'
  namespace :admin do
    resources :users
    resources :posts
  end


  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_one :category
  has_many :comments, :dependent => :destroy
  
  scope :category, -> (category_id) { where category_id: category_id }
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < AdminController
  load_and_authorize_resource
  
  def index
    @posts = Post.all
  end
  
  def new
    @user = User.new
  end

  def create
    @post = Post.create(user_params)
    if @post.save
      flash[:notice] = "Successfully created #{@post.title}"
      redirect_to '/admin/posts'
    else
      render 'new'
    end
  end

  def edit
    @post = Post.find_by_id(params[:id])
  end

  def show
    @post = Post.find(params[:id])

    respond_to do |format|
      format.html
    end
  end

  def update
    @post = Post.find_by_id(params[:id])

    if @post.update(post_params)
      flash[:notice] = "Successfully updated #{@post.title}"
      redirect_to '/admin/posts'
    else
      flash[:alert] = "Unable to update #{@post.title}"
      render 'edit'
    end
  end
  
  def destroy
    @post = Post.find_by_id(params[:id])
    if @post.destroy
      flash[:notice] = "Successfully deleted #{@post.title}"
      redirect_to '/admin/posts'
    else
      flash[:alert] = "#{@post.title} could not be removed."
      render_to '/admin/posts'
    end
  end
  
  private

  def post_params
    params.require(:post).permit(:title, :image, :video, :category_id)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    if params[:category_id].present?
      @posts = Post.category(params[:category_id]).reverse_order
      respond_with(@posts)
    else
      @posts = Post.all.order(:created_at).reverse_order # creates an anonymous scope
      respond_with(@posts)
    end
  end

  def show
    respond_with(@post)
  end

  def new
    @post = Post.new
    respond_with(@post)
  end

  def edit
  end

  def create
    @post = Post.new(post_params)
    @post.user = current_user
    @post.save
    respond_with(@post)
  end

  def update
    @post.update(post_params)
    respond_with(@post)
  end

  def destroy
    @post.destroy
    respond_with(@post)
  end
  
  private
    def set_post
      @post = Post.find(params[:id])
    end

    def post_params
      params.require(:post).permit(:title, :image, :video, :category_id, :body)
    end
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  require 'open-uri'
  
  def embed(url)
    # youtube url
    # http://youtu.be/E3mFLiiNDMQ
    if url.include? "youtube"
      regex = /youtube.com.*(?:\/|v=)([^&$]+)/
      video_id = url.match(regex)[1]
      return content_tag(:iframe,
                         nil,
                         src: "//www.youtube.com/embed/#{video_id}",
                         height: '200px')
    elsif url.include? "youtu.be"
      uri = URI(url)
      return content_tag(:iframe,
                         nil,
                         src: "//www.youtube.com/embed/#{uri.path[1..12]}",
                         height: '200px')

    else
      return content_tag(:iframe,
                         nil,
                         src: url)
    end
  end
  
  def lg_embed(url)
    # youtube url
    if url.include? "youtube"
      regex = /youtube.com.*(?:\/|v=)([^&$]+)/
      video_id = url.match(regex)[1]
      return content_tag(:iframe,
                         nil,
                         src: "//www.youtube.com/embed/#{video_id}",
                         class: "large-video")
    elsif url.include? "youtu.be"
      uri = URI(url)
      return content_tag(:iframe,
                         nil,
                         src: "//www.youtube.com/embed/#{uri.path[1..12]}",
                         class: "large-video")
    else
      return content_tag(:iframe,
                         nil,
                         src: url)
    end
  end
end

app/views/posts/_form.html.erb
<div class="row">
  <%= form_for(@post, 
              html: {class: 'col-md-5 col-md-offset-4 post-form', 
                     role: 'form'}) do |f| %>
    <% if @post.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

        <ul>
          <% @post.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  
    <% if action_name == 'edit' %>
      <% if @post.video != "" %>
        <%= embed(@post.video) %>
      <% else %>
        <%= image_tag "#{@post.image}", :class => "img-responsive" %>
      <% end %>
    <% end %>

    <div class="field form-group post-title">
      <%= f.label :title %><br>
      <%= f.text_field :title,
                       autofocus: true,
                       :class => 'form-control',
                       :required => 'required',
                       :maxlength => 40 %>
    </div>
  
    <div class="field form-group image-field">
      <%= f.label "#{:image} url" %><br>
      <%= f.text_field :image,
                       :class => 'form-control' %>
    </div>

    <div class="field form-group video-field">
      <%= f.label "#{:video} url" %>
      <%= f.text_field :video,
                       :class => 'form-control' %>
    </div>
    
    <div class="field control-group category-field">
      <%= f.label 'Category' %>
      <%= select_tag "post[category_id]",
                     options_from_collection_for_select(Category.all.order(:name), "id", "name", @post.category_id),
                     :class => 'form-control' %>
    </div>

    <div class="actions form-group post-submit">
      <%= f.submit '+',
                   :class => 'btn btn-primary col-sm-2' %>
    </div>
  <% end %>
</div>

app/views/posts/edit.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-4">
    <h3>Editing <%= @post.title %></h3>
    <%= link_to '', @post, :class => 'btn btn-success fa fa-search fa-lg' %>
    <%= link_to '', posts_path, :class => 'btn btn-primary fa fa-rotate-left fa-lg' %>
  </div>
</div>

<%= render 'form' %>

app/views/posts/index.html.erb
<div class="row">
  <div class="col-md-12">
    <%= link_to '', new_post_path, :class => 'btn btn-primary pull-left fa fa-pencil fa-lg' %>
    <%= form_for posts_path, method: 'get',
                             id: 'filter-form',
                             html: {class: 'filter filter-form col-md-4 pull-right'},
                             role: 'form' do %>
      <div class="field control-group">
        <%= select_tag "category_id",
                       options_from_collection_for_select(Category.all.order(:name), "id", "name", params[:category_id] || ""),
                       :prompt => 'All Categories',
                       :class => 'form-control col-md-9',
                       :onchange => "this.form.submit();" %>
      </div>
    <% end %>
  </div>
</div>

<hr>
<div class="row">
  <% @posts.each do |post| %>
    <div class="col-md-4 post-container align-center">
      <h4>
        <%= link_to "#{post.title}", post_path(post) %>
      </h4>
      <% if post.video != "" %>
        <%= embed(post.video) %>
      <% else %>
        <%= image_tag("#{post.image}", class: 'img-responsive') %>
      <% end %>
      <br />
      <span class="text-muted">
        Posted <%= time_ago_in_words(post.created_at) %> ago by 
        <b>
          <% if post.user %>
            <%= post.user.username %>
          <% else %>
            an anonymous member
          <% end %>
        </b>
      </span>
      <br />
      <div class="actions">
        <%= link_to "", post_path(post), :class => 'btn btn-primary action fa fa-search fa-lg' %>
        <% if current_user.id == post.user_id %>
          <%= link_to '', edit_post_path(post), :class => 'btn btn-success fa fa-edit fa-lg' %>
          <%= link_to '', post,
                                    :class => 'btn btn-danger fa fa-eraser fa-lg',
                                    method: :delete,
                                    data: { confirm: 'Are you sure?' } %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/posts/new.html.erb
<div class="row">
  <div class="col-md-4 col-md-offset-4 new-post" id="new-post">
    <h3>New post</h3>
      <button class="add-image btn btn-primary fa fa-image fa-lg" onclick="addImage()"></button>
      <button class="add-video btn btn-primary fa fa-film fa-lg" onclick="addVideo()"></button>

      <%= link_to '', url_for(:back), :class => 'btn btn-primary fa fa-rotate-left fa-lg' %>
  </div>
</div>

<%= render 'form' %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
  <div class="col-sm-12 col-sm-offset-1 view-post">
    <h3>
      <%= @post.title %>
    </h3>
    <% unless current_user.id != @post.user_id %>
      <%= link_to '', edit_post_path(@post), :class => 'btn btn-success fa fa-edit fa-lg' %>
    <% end %>
    <%= link_to '', url_for(:back), :class => 'btn btn-primary fa fa-rotate-left fa-lg' %>
    
    <% if @post.video != "" %>
      <div class="post-video">
        <%= lg_embed(@post.video) %>
      </div>
    <% else %>
      <%= image_tag @post.image, :title => @post.title, :class => "img-responsive" %>
    <% end %>
    
    <h2>Comments</h2>
    <hr class="col-sm-9" />
    <div id="comments">
      <%= form_for [@post, Comment.new], html: {class: 'form col-sm-4', role: 'form'} do |f| %>
        <p class="form-group">
          <%= f.label :body, "New Comment" %>
          <%= f.text_area :body, :class => 'form-control', :required => 'required' %>
        </p>
        <p>
          <%= f.submit "+", :class => 'btn btn-primary col-sm-2' %>
        </p>
      <% end %>
      <%= render :partial => @post.comments %>
    </div>
  </div>
</div>