config/routes.rb
Rails.application.routes.draw do
  resources :comments

  # root
  root 'welcome#index'

  # use devise for users
  devise_for :users

  # resources
  resources :posts do
    resources :comments, :only => [:create]
  end

  # session routes
  devise_scope :user do
    get "/login" => "devise/sessions#new"
    get "/logout" => "devise/sessions#destroy"
  end

  # admin routes
  get '/admin' => 'admin/users#index'
  namespace :admin do
    resources :users
    resources :posts
  end


  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  attr_accessor :login
  has_many :posts, :dependent => :destroy
  has_many :comments, :dependent => :destroy

  validates :username, presence: true
  validates :username, uniqueness: true, if: -> { self.username.present? }
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < AdminController
  load_and_authorize_resource

  def index
  	@users = User.where.not(id: current_user.id)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    if @user.save
      flash[:notice] = 'Successfully created user'
      redirect_to '/admin'
    else
      render 'new'
    end
  end

  def edit
    @user = User.find_by_id(params[:id])
  end

  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html
    end
  end

  def update
    @user = User.find_by_id(params[:id])

    if @user.update(user_params)
      flash[:notice] = 'Successfully updated user'
      redirect_to '/admin/users'
    else
      flash[:alert] = "Unable to update user"
      render 'edit'
    end
  end

  def destroy
    @user = User.find_by_id(params[:id])
    if @user.destroy
      flash[:notice] = "Successfully deleted #{@user.username}"
      redirect_to '/admin/users'
    else
      flash[:alert] = "#{@user.email} could not be removed."
      render_to '/admin/users'
    end
  end


  private

  def user_params
    params.require(:user).permit(:email, :username, :password, :password_confirmation, :admin)
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/edit.html.erb
<%= flash[:alert] %>
<%= flash[:notice] %>

<%= form_for [:admin, @user],
              :role => 'form',
              :class => 'col-sm-4 col-sm-offset-4',
              :method => :put do |f| %>
    <div class="field form-group">
        <%= f.label :email %>
        <%= f.email_field :email,  autofocus: true, :class => 'form-control'%>
    </div>

    <div class="field form-group">
      <%= f.label :password %>
      <%= f.password_field :password, :class => 'form-control' %>
    </div>

    <div class="field form-group">
      <%= f.label :admin %>
      <%= f.check_box :admin, :class => 'checkbox' %>
    </div>

    <div class="actions">
      <%= f.submit 'Update', :class => 'btn btn-primary' %>
    </div>
<% end %>

app/views/admin/users/index.html.erb
<div class="users-section">
  <%= link_to "Add User", new_admin_user_path, :class => 'add-user btn btn-primary btn-sm pull-right' %>
  <table class="users-table table table-striped col-sm-6">
    <thead>
    <tr>
      <td>Email</td>
      <td>Created On</td>
      <td>Admin</td>
      <td></td>
      <td></td>
    </tr>
    </thead>
    <tbody>
    <% @users.each do |user| %>
        <tr>
          <td><%= user.email %></td>
          <td><%= user.created_at %></td>
          <td><%= user.admin %></td>
          <td>
            <%= link_to "Edit", edit_admin_user_path(user),
                                  :class => 'btn btn-success btn-sm'%>
          </td>
          <td>
            <%= button_to "Delete", admin_user_path(user),
                                    :class => 'btn btn-danger btn-sm',
                                    data: { confirm: "Are you sure?" },
                                    method: :delete %>
          </td>
        </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/admin/users/new.html.erb
<%= form_for [:admin, @user], html: {role: 'form', class: 'col-sm-4 col-sm-offset-4'} do |f| %>
  <h4>Add User</h4>
  <%= notice %>
  <%= alert %>
  <hr>
  <div class="field form-group">
    <%= f.label :email %>
    <%= f.email_field :email,
                      autofocus: true,
                      :class => 'form-control',
                      :required => 'required' %>
  </div>

  <div class="field form-group">
    <%= f.label :username %>
    <%= f.text_field :username,
                     :class => 'form-control',
                     :required => 'required' %>
  </div>

  <div class="field form-group">
    <%= f.label :password %>
    <%= f.password_field :password,
                         :class => 'form-control',
                         :required => 'required' %>
  </div>

  <div class="field form-group">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation,
                         autocomplete: "off",
                         :class => 'form-control',
                         :required => 'required' %>
  </div>

  <div class="field form-group">
    <%= f.label :admin %><br />
    <%= f.check_box :admin %>
  </div>

  <div class="actions">
    <%= f.submit 'Add User', :class => 'btn btn-primary' %>
  </div>
<% end %>

app/views/admin/users/show.html.erb
<%= form_for([:admin, @user], 
              :role => 'form',
              :method => :put,
              html: {class: 'col-sm-4 col-sm-offset-4'}) do |f| %>
  <h2>Profile</h2>

  <div class="field form-group">
    <%= f.label :email %><br />
    <%= f.email_field :email,
                      :class => 'form-control',
                      autofocus: true %>
  </div>

  <div class="field form-group">
    <%= f.label :username %><br />
    <%= f.text_field :username,
                      :class => 'form-control',
                      autofocus: true %>
  </div>

  <div class="field form-group">
    <%= f.label :password %> <i>(leave blank if you don't want to change it)</i><br />
    <%= f.password_field :password,
                         :class => 'form-control',
                         autocomplete: "off" %>
  </div>

  <div class="field form-group">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation,
                         :class => 'form-control',
                         autocomplete: "off" %>
  </div>

  <div class="field form-group">
    <%= f.label :current_password %>
    <i>(we need your current password to confirm your changes)</i><br />
    <%= f.password_field :current_password,
                         :class => 'form-control',
                         autocomplete: "off",
                         :required => 'required' %>
  </div>

  <div class="actions form-group col-sm-6">
    <%= f.submit "Update", :class => 'btn btn-primary' %>
  </div>
    <div class="form-group col-sm-6">
      <%= link_to "Back", :back, :class => 'btn btn-primary' %>
    </div>
    <h3>Cancel my account</h3>
    <div class="form-group">
      <p>Unhappy? <%= button_to "Cancel my account", registration_path(@user),
                                :class => 'btn btn-danger',
                                data: { confirm: "Are you sure?" },
                                method: :delete %></p>
    </div>

<% end %>