config/routes.rb
Rails.application.routes.draw do
  resources :comments

  # root
  root 'welcome#index'

  # use devise for users
  devise_for :users

  # resources
  resources :posts do
    resources :comments, :only => [:create]
  end

  # session routes
  devise_scope :user do
    get "/login" => "devise/sessions#new"
    get "/logout" => "devise/sessions#destroy"
  end

  # admin routes
  get '/admin' => 'admin/users#index'
  namespace :admin do
    resources :users
    resources :posts
  end


  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/views/layouts/_chat.html.erb
<% if user_signed_in? %>
  <section class="chat-container">
  	<button class="chat-button btn btn-success">
  	  <span class="fa fa-weixin fa-lg"></span>
  	</button>
  	<div class="chat-area">
		
  	</div>
  	<input type="text" id="chat-message" placeholder="Message">
  </section>
<% end %>

app/views/layouts/_navigation.html.erb
<div class="navbar navbar-inverse">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-inverse-collapse">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="/">berb.</a>
  </div>
  <div class="navbar-collapse collapse navbar-inverse-collapse">
    <ul class="nav navbar-nav">
      <% if user_signed_in? %>
        <li class="<%= 'active' if params[:controller] == 'welcome' %>">
          <%= link_to "", root_path, :class => 'fa fa-home fa-lg' %>
        </li>
        <li class="<%= 'active' if params[:controller] == 'posts' %>">
          <%= link_to '', posts_path, :class => 'fa fa-newspaper-o fa-lg' %>
        </li>
      <% end %>
    </ul>
    <!-- <form class="navbar-form navbar-left">
      <input type="text" class="form-control col-lg-8" placeholder="Search">
    </form> -->
    <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in? %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_user.email %><b class="caret"></b></a>
          <ul class="dropdown-menu">
            <% if current_user.admin %>
              <li>
                <%= link_to "", edit_user_registration_path, :class => 'fa fa-male fa-lg' %>
              </li>
              <li>
                <%= link_to 'God Mode', '/admin' %>
              </li>
            <% else %>
              <li>
                <%= link_to '', edit_user_registration_path, :class => 'fa fa-male fa-lg' %>
              </li>
            <% end %>
            <li class="divider"></li>
            <li>
              <%= link_to '', destroy_user_session_path, :method => :delete, :class => 'fa fa-power-off fa-lg' %>
            </li>
          </ul>
        </li>
      <% else %>
        <li>
          <%= link_to('Login', new_user_session_path)  %>
        </li>
        <li>
          <%= link_to('Register', new_user_registration_path)  %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>berb.</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render 'layouts/navigation' %>
    <div class="container">
      <ul class="nav nav-pills">
        <li role="presentation" class="<%= 'active' if params[:controller] == 'admin/users' %>">
          <%= link_to "Users", admin_users_path %>
        </li>
        <li role="presentation" class="<%= 'active' if params[:controller] == 'admin/posts' %>">
          <%= link_to "Posts", admin_posts_path %>
        </li>
      </ul>
      <%= yield %>
    </div>
    <%= render 'layouts/chat' %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>berb.</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
    <script src='https://cdn.firebase.com/js/client/2.0.4/firebase.js'></script>
    <%= csrf_meta_tags %>
    <!-- adding global username for live chat use -->
    <% if user_signed_in? %>
      <%= javascript_tag do %>
        window.username = '<%= j current_user.username %>';
      <% end %>
    <% end %>
  </head>
  <body class="<%= controller_name %> <%= action_name %>">
    <%= render 'layouts/navigation' %>
    <div class="container">
      <% if notice %>
          <div class="alert alert-success alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert">
              <span aria-hidden="true">&times;</span><span class="sr-only">Close</span>
            </button>
            <%= notice %>
          </div>
      <% end %>
      <% if alert %>
          <div class="alert alert-danger alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert">
              <span aria-hidden="true">&times;</span><span class="sr-only">Close</span>
            </button>
            <%= alert %>
          </div>
      <% end %>
      <%= yield %>
    </div>
    <%= render 'layouts/chat' %>
  </body>
</html>